### ISSUE TITLE
Foldlevel is lost when switching tabs

### ISSUE THREAD

**Issue by armw4** [koron/minimap-vim#20]
Does not maintain state of folds when swapping tabs. If all text is initially folded, and I later unfold it, the minimap does not update.

![Screen Shot 2013-04-10 at 11 57 13 AM](https://f.cloud.github.com/assets/246377/363039/5d7f7102-a1f7-11e2-93d5-cf6e78639b3b.png)

**Comment by koron** [comment]
I won't fix this.  But patches might be welcome.

**Comment by armw4** [comment]
👍
