### ISSUE TITLE
There's no way i can use this today?

### ISSUE THREAD

**Issue by hrqmonteiro** [koron/minimap-vim#25]
I know the repo looks abandoned. But i tried to install and get this error:

```
Error detected while processing function minimap#_sync[2]..minimap#_is_open:
line    1:
E730: using List as a String
```

There's a way i can fix it and try to use it?

**Comment by koron** [comment]
i can't reproduce the error with my env, Vim 8.2.1287,

do you use with neovim?
minimap-vim supports and been tested, only Vim.

**Comment by koron** [comment]
ah sorry, minimap-vim requires gvim, GUI feature enabled.

> It only works with Gvim or MacVim

You can see this in README.mkd

**Comment by hrqmonteiro** [comment]
I was using Neovim, yes.

Now i installed Gvim just for testing it, still doesn't work here.

I am on `version 8.2.1948`.

I copied all the contents to the `.vim` folder, opened Gvim, did the `:MinimapSync` and no minimap shows up:

![2020-12-31_01-40](https://user-images.githubusercontent.com/17055027/103394772-420eff00-4b09-11eb-94b4-f0072c70c205.png)

**Comment by hrqmonteiro** [comment]
Actually, now, after i did the `MinimapSync`, it opened, but in a very strange way.

It opened a window on the left, with a light colorscheme, on the same size of my main window, including the font size:

![2020-12-31_01-54](https://user-images.githubusercontent.com/17055027/103395122-3a505a00-4b0b-11eb-891f-002da5474fe4.png)
